{% set name = "nameco" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nameco-{{ version }}.tar.gz
  sha256: c1aa9e2e8636d93af7f86edbd365b2eae201136da1aeb723dfc9f0b0065fe921

build:
  entry_points:
    - nameco = lib.run_nameco:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=61.0
    - pip
  run:
    - python >=3.8

test:
  imports:
    - nameco
  commands:
    - pip check
    - nameco --help
  requires:
    - pip

about:
  dev_url: https://github.com/timyerg/NaMeco
  home: https://pypi.org/project/nameco/
  summary: Pipeline for the Nanopore 16S long read clustering and taxonomy classification
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timyerg
